# Generated by Django 4.2.3 on 2023-07-12 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdetails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
